repos:
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: [-i, --expand-star-imports]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: [-i, '--ignore=E26,E265,E266,E501,E722']
    -   id: autopep8
        name: autopep8 (trailing whitespace)
        args: [-i, -a, --select=W291]
