# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Brain\pylabnet\pylabnet\gui\pyqt\gui_templates\fit_popup_hist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(998, 101)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.model_type = QtWidgets.QComboBox(Form)
        self.model_type.setObjectName("model_type")
        self.model_type.addItem("")
        self.gridLayout.addWidget(self.model_type, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Fit Parameters"))
        self.model_type.setItemText(0, _translate("Form", "Exponential Decay (T1 measurement)"))
