# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit_params.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(982, 793)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 961, 781))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.main = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.main.setContentsMargins(0, 0, 0, 0)
        self.main.setObjectName("main")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
