name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up CI environment
      run: |
        python setup.py ci
    - name: Run check.py
      run: |
        python check.py ${GITHUB_BASE_REF:-$GITHUB_SHA~}..${GITHUB_HEAD_REF:-$GITHUB_SHA}
