name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up development environment
      run: |
        python setup.py develop
    - name: Run check.py
      run: |
        python check.py ${GITHUB_BASE_REF:-HEAD^}..HEAD
